security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        api_login:
            pattern: ^/api/login_check$
            provider: app_user_provider
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            login_throttling:
                max_attempts: 1000
                interval: '1 minute'

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: '^/api/login_check$', roles: PUBLIC_ACCESS }
        - { path: '^/api/contexts', roles: PUBLIC_ACCESS }
