<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260506120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add manga_follow table and custom_list_manga pivot table for follow and custom list features';
    }

    public function up(Schema $schema): void
    {
        // Create manga_follow table
        $this->addSql('CREATE TABLE manga_follow (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, followed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, manga_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX idx_manga_follow_user_manga ON manga_follow (user_id, manga_id)');
        $this->addSql('CREATE INDEX IDX_7A1C33C5A76ED395 ON manga_follow (user_id)');
        $this->addSql('CREATE INDEX IDX_7A1C33C57B6461 ON manga_follow (manga_id)');

        // Create custom_list_manga pivot table
        $this->addSql('CREATE TABLE custom_list_manga (custom_list_id INT NOT NULL, manga_id INT NOT NULL, PRIMARY KEY (custom_list_id, manga_id))');
        $this->addSql('CREATE INDEX IDX_9743D85B51C98D58 ON custom_list_manga (custom_list_id)');
        $this->addSql('CREATE INDEX IDX_9743D85B7B6461 ON custom_list_manga (manga_id)');

        // Add foreign key constraints for manga_follow
        $this->addSql('ALTER TABLE manga_follow ADD CONSTRAINT FK_7A1C33C5A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE manga_follow ADD CONSTRAINT FK_7A1C33C57B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE');

        // Add foreign key constraints for custom_list_manga
        $this->addSql('ALTER TABLE custom_list_manga ADD CONSTRAINT FK_9743D85B51C98D58 FOREIGN KEY (custom_list_id) REFERENCES custom_list (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE custom_list_manga ADD CONSTRAINT FK_9743D85B7B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // Remove foreign key constraints
        $this->addSql('ALTER TABLE manga_follow DROP CONSTRAINT FK_7A1C33C5A76ED395');
        $this->addSql('ALTER TABLE manga_follow DROP CONSTRAINT FK_7A1C33C57B6461');
        $this->addSql('ALTER TABLE custom_list_manga DROP CONSTRAINT FK_9743D85B51C98D58');
        $this->addSql('ALTER TABLE custom_list_manga DROP CONSTRAINT FK_9743D85B7B6461');

        // Drop tables
        $this->addSql('DROP TABLE manga_follow');
        $this->addSql('DROP TABLE custom_list_manga');
    }
}
