<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260504141717 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cover_art (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_path VARCHAR(500) NOT NULL, volume VARCHAR(50) DEFAULT NULL, is_primary BOOLEAN DEFAULT false NOT NULL, manga_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4EA5C33D7B6461 ON cover_art (manga_id)');
        $this->addSql('CREATE INDEX IDX_4EA5C33DB99ACDDE ON cover_art (volume)');
        $this->addSql('CREATE TABLE custom_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, visibility VARCHAR(20) NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_45BE30E5A76ED395 ON custom_list (user_id)');
        $this->addSql('CREATE TABLE manga_tag (manga_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (manga_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_52E8F5BA7B6461 ON manga_tag (manga_id)');
        $this->addSql('CREATE INDEX IDX_52E8F5BABAD26311 ON manga_tag (tag_id)');
        $this->addSql('CREATE TABLE scanlation_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, website VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9B892DAC5E237E06 ON scanlation_group (name)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, group_name VARCHAR(50) NOT NULL, is_primary BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_389B78377792576 ON tag (group_name)');
        $this->addSql('CREATE TABLE tag_manga (tag_id INT NOT NULL, manga_id INT NOT NULL, PRIMARY KEY (tag_id, manga_id))');
        $this->addSql('CREATE INDEX IDX_54B68705BAD26311 ON tag_manga (tag_id)');
        $this->addSql('CREATE INDEX IDX_54B687057B6461 ON tag_manga (manga_id)');
        $this->addSql('ALTER TABLE cover_art ADD CONSTRAINT FK_4EA5C33D7B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE custom_list ADD CONSTRAINT FK_45BE30E5A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE manga_tag ADD CONSTRAINT FK_52E8F5BA7B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE manga_tag ADD CONSTRAINT FK_52E8F5BABAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tag_manga ADD CONSTRAINT FK_54B68705BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tag_manga ADD CONSTRAINT FK_54B687057B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE app_user ADD username VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE app_user ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE app_user ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9F85E0677 ON app_user (username)');
        $this->addSql('ALTER INDEX uniq_identifier_email RENAME TO UNIQ_88BDF3E9E7927C74');
        $this->addSql('ALTER TABLE chapter ADD scanlation_group_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE chapter ADD CONSTRAINT FK_F981B52E26D00C4 FOREIGN KEY (scanlation_group_id) REFERENCES scanlation_group (id)');
        $this->addSql('CREATE INDEX IDX_F981B52E26D00C4 ON chapter (scanlation_group_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cover_art DROP CONSTRAINT FK_4EA5C33D7B6461');
        $this->addSql('ALTER TABLE custom_list DROP CONSTRAINT FK_45BE30E5A76ED395');
        $this->addSql('ALTER TABLE manga_tag DROP CONSTRAINT FK_52E8F5BA7B6461');
        $this->addSql('ALTER TABLE manga_tag DROP CONSTRAINT FK_52E8F5BABAD26311');
        $this->addSql('ALTER TABLE tag_manga DROP CONSTRAINT FK_54B68705BAD26311');
        $this->addSql('ALTER TABLE tag_manga DROP CONSTRAINT FK_54B687057B6461');
        $this->addSql('DROP TABLE cover_art');
        $this->addSql('DROP TABLE custom_list');
        $this->addSql('DROP TABLE manga_tag');
        $this->addSql('DROP TABLE scanlation_group');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE tag_manga');
        $this->addSql('DROP INDEX UNIQ_88BDF3E9F85E0677');
        $this->addSql('ALTER TABLE app_user DROP username');
        $this->addSql('ALTER TABLE app_user ALTER id SET DEFAULT nextval(\'app_user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE app_user ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_88bdf3e9e7927c74 RENAME TO uniq_identifier_email');
        $this->addSql('ALTER TABLE chapter DROP CONSTRAINT FK_F981B52E26D00C4');
        $this->addSql('DROP INDEX IDX_F981B52E26D00C4');
        $this->addSql('ALTER TABLE chapter DROP scanlation_group_id');
    }
}
