<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260505155701 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9F85E0677 ON app_user (username)');
        $this->addSql('CREATE TABLE chapter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, volume VARCHAR(50) DEFAULT NULL, chapter_number VARCHAR(50) NOT NULL, title VARCHAR(255) DEFAULT NULL, language VARCHAR(10) NOT NULL, pages JSON NOT NULL, manga_id INT NOT NULL, scanlation_group_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F981B52E7B6461 ON chapter (manga_id)');
        $this->addSql('CREATE INDEX IDX_F981B52E26D00C4 ON chapter (scanlation_group_id)');
        $this->addSql('CREATE INDEX IDX_F981B52ED4DB71B5 ON chapter (language)');
        $this->addSql('CREATE INDEX IDX_F981B52ECDCEF8DF ON chapter (chapter_number)');
        $this->addSql('CREATE TABLE cover_art (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, image_path VARCHAR(500) NOT NULL, volume VARCHAR(50) DEFAULT NULL, is_primary BOOLEAN DEFAULT false NOT NULL, manga_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4EA5C33D7B6461 ON cover_art (manga_id)');
        $this->addSql('CREATE INDEX IDX_4EA5C33DB99ACDDE ON cover_art (volume)');
        $this->addSql('CREATE TABLE creator (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BC06EA638CDE5729 ON creator (type)');
        $this->addSql('CREATE TABLE custom_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, visibility VARCHAR(20) NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_45BE30E5A76ED395 ON custom_list (user_id)');
        $this->addSql('CREATE TABLE manga (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, title VARCHAR(255) NOT NULL, alt_titles JSON DEFAULT NULL, description TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, year INT DEFAULT NULL, content_rating VARCHAR(30) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_765A9E037B00651C ON manga (status)');
        $this->addSql('CREATE INDEX IDX_765A9E03BB827337 ON manga (year)');
        $this->addSql('CREATE INDEX IDX_765A9E03B0BF568E ON manga (content_rating)');
        $this->addSql('CREATE TABLE manga_creator (manga_id INT NOT NULL, creator_id INT NOT NULL, PRIMARY KEY (manga_id, creator_id))');
        $this->addSql('CREATE INDEX IDX_22B13F627B6461 ON manga_creator (manga_id)');
        $this->addSql('CREATE INDEX IDX_22B13F6261220EA6 ON manga_creator (creator_id)');
        $this->addSql('CREATE TABLE manga_tag (manga_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (manga_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_52E8F5BA7B6461 ON manga_tag (manga_id)');
        $this->addSql('CREATE INDEX IDX_52E8F5BABAD26311 ON manga_tag (tag_id)');
        $this->addSql('CREATE TABLE scanlation_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, website VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9B892DAC5E237E06 ON scanlation_group (name)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, group_name VARCHAR(50) NOT NULL, is_primary BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_389B78377792576 ON tag (group_name)');
        $this->addSql('ALTER TABLE chapter ADD CONSTRAINT FK_F981B52E7B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chapter ADD CONSTRAINT FK_F981B52E26D00C4 FOREIGN KEY (scanlation_group_id) REFERENCES scanlation_group (id)');
        $this->addSql('ALTER TABLE cover_art ADD CONSTRAINT FK_4EA5C33D7B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE custom_list ADD CONSTRAINT FK_45BE30E5A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE manga_creator ADD CONSTRAINT FK_22B13F627B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE manga_creator ADD CONSTRAINT FK_22B13F6261220EA6 FOREIGN KEY (creator_id) REFERENCES creator (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE manga_tag ADD CONSTRAINT FK_52E8F5BA7B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE manga_tag ADD CONSTRAINT FK_52E8F5BABAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chapter DROP CONSTRAINT FK_F981B52E7B6461');
        $this->addSql('ALTER TABLE chapter DROP CONSTRAINT FK_F981B52E26D00C4');
        $this->addSql('ALTER TABLE cover_art DROP CONSTRAINT FK_4EA5C33D7B6461');
        $this->addSql('ALTER TABLE custom_list DROP CONSTRAINT FK_45BE30E5A76ED395');
        $this->addSql('ALTER TABLE manga_creator DROP CONSTRAINT FK_22B13F627B6461');
        $this->addSql('ALTER TABLE manga_creator DROP CONSTRAINT FK_22B13F6261220EA6');
        $this->addSql('ALTER TABLE manga_tag DROP CONSTRAINT FK_52E8F5BA7B6461');
        $this->addSql('ALTER TABLE manga_tag DROP CONSTRAINT FK_52E8F5BABAD26311');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE chapter');
        $this->addSql('DROP TABLE cover_art');
        $this->addSql('DROP TABLE creator');
        $this->addSql('DROP TABLE custom_list');
        $this->addSql('DROP TABLE manga');
        $this->addSql('DROP TABLE manga_creator');
        $this->addSql('DROP TABLE manga_tag');
        $this->addSql('DROP TABLE scanlation_group');
        $this->addSql('DROP TABLE tag');
    }
}
