<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260504003908 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chapter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, volume VARCHAR(50) DEFAULT NULL, chapter_number VARCHAR(50) NOT NULL, title VARCHAR(255) DEFAULT NULL, language VARCHAR(10) NOT NULL, pages JSON NOT NULL, manga_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F981B52E7B6461 ON chapter (manga_id)');
        $this->addSql('CREATE TABLE creator (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE manga (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, alt_titles JSON DEFAULT NULL, description TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, year INT DEFAULT NULL, content_rating VARCHAR(30) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE manga_creator (manga_id INT NOT NULL, creator_id INT NOT NULL, PRIMARY KEY (manga_id, creator_id))');
        $this->addSql('CREATE INDEX IDX_22B13F627B6461 ON manga_creator (manga_id)');
        $this->addSql('CREATE INDEX IDX_22B13F6261220EA6 ON manga_creator (creator_id)');
        $this->addSql('ALTER TABLE chapter ADD CONSTRAINT FK_F981B52E7B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE manga_creator ADD CONSTRAINT FK_22B13F627B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE manga_creator ADD CONSTRAINT FK_22B13F6261220EA6 FOREIGN KEY (creator_id) REFERENCES creator (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chapter DROP CONSTRAINT FK_F981B52E7B6461');
        $this->addSql('ALTER TABLE manga_creator DROP CONSTRAINT FK_22B13F627B6461');
        $this->addSql('ALTER TABLE manga_creator DROP CONSTRAINT FK_22B13F6261220EA6');
        $this->addSql('DROP TABLE chapter');
        $this->addSql('DROP TABLE creator');
        $this->addSql('DROP TABLE manga');
        $this->addSql('DROP TABLE manga_creator');
    }
}
